name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag debiancurl:bookworm
    - name: Auto Docker Push
      # You may pin to the exact commit or the version.
      # uses: bozdoz/auto-docker-push@4b66f8aac49b399c209193b9ab9091e6aa80ee51
      uses: bozdoz/auto-docker-push@v2.0.0-published-action
      with:
        # Name of image
        image: debiancurl:bookworm
        # Docker Hub username'
        username: alexanderfernandez
        # Docker Hub password'
        password: dckr_pat_6MlORjlJMYZhn792NPd9BujYBiw
